spring:
  redis:
    host: redis
    port: 6379
    password:
    timeout: 60000
    
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    exchange: microservices-exchange
    routingkey:
      task-created: task.created
